### ISSUE TITLE
Donate Page

### ISSUE THREAD

**Issue by Jillzey** [CodeForCharlotte/laddrdocs#14]
Duplicate a similar donate page to what we have but connect it directly to the CFC bank account since we no longer need CFA to accept payment (unless 501c3 is required)

**Comment by RowdyChildren** [comment]
I agree, when we get 501(c)3 status we should have our own donate page, technology wise are we looking towards PayPal or rolling our own solution with something pike stripe?

**Comment by RowdyChildren** [comment]
This issue was moved to CodeForCharlotte/codeforcharlotte.org#104
